# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientcontacts.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewCustomerContacts(object):
    def setupUi(self, NewCustomerContacts):
        NewCustomerContacts.setObjectName("NewCustomerContacts")
        NewCustomerContacts.resize(921, 321)
        NewCustomerContacts.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(NewCustomerContacts)
        self.centralwidget.setObjectName("centralwidget")
        self.customerTable = QtWidgets.QTableWidget(self.centralwidget)
        self.customerTable.setGeometry(QtCore.QRect(390, 10, 521, 300))
        self.customerTable.setObjectName("customerTable")
        self.customerTable.setColumnCount(0)
        self.customerTable.setRowCount(0)
        self.SearchCustomerButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchCustomerButton.setGeometry(QtCore.QRect(160, 200, 80, 25))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SearchCustomerButton.setFont(font)
        self.SearchCustomerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SearchCustomerButton.setStyleSheet("QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: rgb(85, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: white;\n"
"}\n"
"")
        self.SearchCustomerButton.setObjectName("SearchCustomerButton")
        self.lineName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineName.setGeometry(QtCore.QRect(130, 70, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineName.setFont(font)
        self.lineName.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.lineName.setText("")
        self.lineName.setObjectName("lineName")
        self.lineSurname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSurname.setGeometry(QtCore.QRect(130, 110, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineSurname.setFont(font)
        self.lineSurname.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.lineSurname.setText("")
        self.lineSurname.setObjectName("lineSurname")
        self.lineNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.lineNumber.setGeometry(QtCore.QRect(130, 150, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineNumber.setFont(font)
        self.lineNumber.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.lineNumber.setText("")
        self.lineNumber.setObjectName("lineNumber")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(150, 234, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.exitButton.setFont(font)
        self.exitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitButton.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgbrgb(240, 255, 255);\n"
"    color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: black;\n"
"}\n"
"")
        self.exitButton.setObjectName("exitButton")
        NewCustomerContacts.setCentralWidget(self.centralwidget)

        self.retranslateUi(NewCustomerContacts)
        QtCore.QMetaObject.connectSlotsByName(NewCustomerContacts)

    def retranslateUi(self, NewCustomerContacts):
        _translate = QtCore.QCoreApplication.translate
        NewCustomerContacts.setWindowTitle(_translate("NewCustomerContacts", "Контакты"))
        self.SearchCustomerButton.setText(_translate("NewCustomerContacts", "Поиск"))
        self.lineName.setPlaceholderText(_translate("NewCustomerContacts", "Инициалы"))
        self.lineSurname.setPlaceholderText(_translate("NewCustomerContacts", "Паспорт"))
        self.lineNumber.setPlaceholderText(_translate("NewCustomerContacts", "Телефон"))
        self.exitButton.setText(_translate("NewCustomerContacts", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewCustomerContacts = QtWidgets.QMainWindow()
    ui = Ui_NewCustomerContacts()
    ui.setupUi(NewCustomerContacts)
    NewCustomerContacts.show()
    sys.exit(app.exec_())
