# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'decoration.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(985, 659)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.newTourButton = QtWidgets.QPushButton(self.centralwidget)
        self.newTourButton.setGeometry(QtCore.QRect(160, 510, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.newTourButton.setFont(font)
        self.newTourButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newTourButton.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgbrgb(240, 255, 255);\n"
"    color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: black;\n"
"}\n"
"")
        self.newTourButton.setObjectName("newTourButton")
        self.initials = QtWidgets.QLineEdit(self.centralwidget)
        self.initials.setGeometry(QtCore.QRect(80, 40, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.initials.setFont(font)
        self.initials.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.initials.setText("")
        self.initials.setObjectName("initials")
        self.passport = QtWidgets.QLineEdit(self.centralwidget)
        self.passport.setGeometry(QtCore.QRect(80, 100, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passport.setFont(font)
        self.passport.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.passport.setText("")
        self.passport.setObjectName("passport")
        self.phone = QtWidgets.QLineEdit(self.centralwidget)
        self.phone.setGeometry(QtCore.QRect(80, 160, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.phone.setFont(font)
        self.phone.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.phone.setText("")
        self.phone.setObjectName("phone")
        self.date = QtWidgets.QLineEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(80, 220, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.date.setFont(font)
        self.date.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.date.setText("")
        self.date.setObjectName("date")
        self.city = QtWidgets.QLineEdit(self.centralwidget)
        self.city.setGeometry(QtCore.QRect(310, 160, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.city.setFont(font)
        self.city.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.city.setText("")
        self.city.setObjectName("city")
        self.adults = QtWidgets.QLineEdit(self.centralwidget)
        self.adults.setGeometry(QtCore.QRect(80, 280, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.adults.setFont(font)
        self.adults.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.adults.setText("")
        self.adults.setObjectName("adults")
        self.nights = QtWidgets.QLineEdit(self.centralwidget)
        self.nights.setGeometry(QtCore.QRect(80, 400, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nights.setFont(font)
        self.nights.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.nights.setText("")
        self.nights.setObjectName("nights")
        self.adults_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.adults_2.setGeometry(QtCore.QRect(80, 340, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.adults_2.setFont(font)
        self.adults_2.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.adults_2.setText("")
        self.adults_2.setMaxLength(32762)
        self.adults_2.setObjectName("adults_2")
        self.type_tour = QtWidgets.QLineEdit(self.centralwidget)
        self.type_tour.setGeometry(QtCore.QRect(310, 210, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.type_tour.setFont(font)
        self.type_tour.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.type_tour.setText("")
        self.type_tour.setObjectName("type_tour")
        self.type_nutrition = QtWidgets.QLineEdit(self.centralwidget)
        self.type_nutrition.setGeometry(QtCore.QRect(310, 260, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.type_nutrition.setFont(font)
        self.type_nutrition.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.type_nutrition.setText("")
        self.type_nutrition.setObjectName("type_nutrition")
        self.name_hotel = QtWidgets.QLineEdit(self.centralwidget)
        self.name_hotel.setGeometry(QtCore.QRect(310, 310, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name_hotel.setFont(font)
        self.name_hotel.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.name_hotel.setText("")
        self.name_hotel.setObjectName("name_hotel")
        self.newCityButton = QtWidgets.QPushButton(self.centralwidget)
        self.newCityButton.setGeometry(QtCore.QRect(499, 520, 191, 50))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.newCityButton.setFont(font)
        self.newCityButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newCityButton.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgbrgb(240, 255, 255);\n"
"    color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: black;\n"
"}\n"
"")
        self.newCityButton.setObjectName("newCityButton")
        self.newTypeButton = QtWidgets.QPushButton(self.centralwidget)
        self.newTypeButton.setGeometry(QtCore.QRect(700, 520, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.newTypeButton.setFont(font)
        self.newTypeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newTypeButton.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgbrgb(240, 255, 255);\n"
"    color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: black;\n"
"}\n"
"")
        self.newTypeButton.setObjectName("newTypeButton")
        self.newNutritionButton = QtWidgets.QPushButton(self.centralwidget)
        self.newNutritionButton.setGeometry(QtCore.QRect(499, 580, 191, 50))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.newNutritionButton.setFont(font)
        self.newNutritionButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newNutritionButton.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgbrgb(240, 255, 255);\n"
"    color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: black;\n"
"}\n"
"")
        self.newNutritionButton.setObjectName("newNutritionButton")
        self.newIDButton = QtWidgets.QPushButton(self.centralwidget)
        self.newIDButton.setGeometry(QtCore.QRect(700, 580, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.newIDButton.setFont(font)
        self.newIDButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newIDButton.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgbrgb(240, 255, 255);\n"
"    color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: black;\n"
"}\n"
"")
        self.newIDButton.setObjectName("newIDButton")
        self.tableShow = QtWidgets.QTableView(self.centralwidget)
        self.tableShow.setGeometry(QtCore.QRect(510, 10, 400, 500))
        self.tableShow.setObjectName("tableShow")
        self.newExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.newExitButton.setGeometry(QtCore.QRect(160, 570, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.newExitButton.setFont(font)
        self.newExitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newExitButton.setStyleSheet("QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: rgb(85, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: white;\n"
"}\n"
"")
        self.newExitButton.setObjectName("newExitButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BusinessAssistant"))
        self.newTourButton.setText(_translate("MainWindow", "Оформить тур"))
        self.initials.setPlaceholderText(_translate("MainWindow", "Инициалы"))
        self.passport.setPlaceholderText(_translate("MainWindow", "Паспорт"))
        self.phone.setPlaceholderText(_translate("MainWindow", "Телефон"))
        self.date.setPlaceholderText(_translate("MainWindow", "Дата вылета"))
        self.city.setPlaceholderText(_translate("MainWindow", "Город вылета"))
        self.adults.setPlaceholderText(_translate("MainWindow", "Число взрослых"))
        self.nights.setPlaceholderText(_translate("MainWindow", "Количество ночей"))
        self.adults_2.setPlaceholderText(_translate("MainWindow", "Число детей"))
        self.type_tour.setPlaceholderText(_translate("MainWindow", "Тип тура"))
        self.type_nutrition.setPlaceholderText(_translate("MainWindow", "Тип питания"))
        self.name_hotel.setPlaceholderText(_translate("MainWindow", "Название отеля"))
        self.newCityButton.setText(_translate("MainWindow", "Города"))
        self.newTypeButton.setText(_translate("MainWindow", "Типы туров"))
        self.newNutritionButton.setText(_translate("MainWindow", "Типы питания"))
        self.newIDButton.setText(_translate("MainWindow", "ID отелей"))
        self.newExitButton.setText(_translate("MainWindow", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
