# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newclient.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineSurname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSurname.setGeometry(QtCore.QRect(100, 100, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineSurname.setFont(font)
        self.lineSurname.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.lineSurname.setText("")
        self.lineSurname.setObjectName("lineSurname")
        self.lineName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineName.setGeometry(QtCore.QRect(100, 50, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineName.setFont(font)
        self.lineName.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.lineName.setText("")
        self.lineName.setObjectName("lineName")
        self.createCustomerButton = QtWidgets.QPushButton(self.centralwidget)
        self.createCustomerButton.setGeometry(QtCore.QRect(150, 200, 100, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.createCustomerButton.setFont(font)
        self.createCustomerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.createCustomerButton.setStyleSheet("QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: rgb(85, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: white;\n"
"}\n"
"")
        self.createCustomerButton.setObjectName("createCustomerButton")
        self.exitCreateCustomerButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitCreateCustomerButton.setGeometry(QtCore.QRect(150, 240, 100, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exitCreateCustomerButton.setFont(font)
        self.exitCreateCustomerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitCreateCustomerButton.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgbrgb(240, 255, 255);\n"
"    color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: black;\n"
"}\n"
"")
        self.exitCreateCustomerButton.setObjectName("exitCreateCustomerButton")
        self.lineNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.lineNumber.setGeometry(QtCore.QRect(100, 150, 200, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineNumber.setFont(font)
        self.lineNumber.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.lineNumber.setText("")
        self.lineNumber.setObjectName("lineNumber")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Новый клиент"))
        self.lineSurname.setPlaceholderText(_translate("MainWindow", "Паспорт"))
        self.lineName.setPlaceholderText(_translate("MainWindow", "Инициалы"))
        self.createCustomerButton.setText(_translate("MainWindow", "Создать"))
        self.exitCreateCustomerButton.setText(_translate("MainWindow", "Выход"))
        self.lineNumber.setPlaceholderText(_translate("MainWindow", "Телефон"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
