# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 450)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login = QtWidgets.QLineEdit(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(150, 140, 420, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login.setFont(font)
        self.login.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.login.setText("")
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(150, 200, 420, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password.setFont(font)
        self.password.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 540, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setStyleSheet("color: black;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.radioManagerButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioManagerButton.setGeometry(QtCore.QRect(240, 290, 130, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioManagerButton.setFont(font)
        self.radioManagerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioManagerButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.radioManagerButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioManagerButton.setAutoFillBackground(False)
        self.radioManagerButton.setStyleSheet("")
        self.radioManagerButton.setObjectName("radioManagerButton")
        self.radioWorkerButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioWorkerButton.setGeometry(QtCore.QRect(390, 290, 130, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioWorkerButton.setFont(font)
        self.radioWorkerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioWorkerButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.radioWorkerButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioWorkerButton.setAutoFillBackground(False)
        self.radioWorkerButton.setStyleSheet("")
        self.radioWorkerButton.setObjectName("radioWorkerButton")
        self.SingInWindowButton = QtWidgets.QPushButton(self.centralwidget)
        self.SingInWindowButton.setGeometry(QtCore.QRect(150, 350, 200, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SingInWindowButton.setFont(font)
        self.SingInWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SingInWindowButton.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgbrgb(240, 255, 255);\n"
"    color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: black;\n"
"}\n"
"")
        self.SingInWindowButton.setObjectName("SingInWindowButton")
        self.RegistrButton = QtWidgets.QPushButton(self.centralwidget)
        self.RegistrButton.setGeometry(QtCore.QRect(370, 350, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.RegistrButton.setFont(font)
        self.RegistrButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RegistrButton.setStyleSheet("QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: rgb(85, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: white;\n"
"}\n"
"")
        self.RegistrButton.setObjectName("RegistrButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Регистрация"))
        self.login.setPlaceholderText(_translate("MainWindow", "Логин"))
        self.password.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.label.setText(_translate("MainWindow", "Создайте аккаунт"))
        self.radioManagerButton.setText(_translate("MainWindow", "Клиент"))
        self.radioWorkerButton.setText(_translate("MainWindow", "Сотрудник"))
        self.SingInWindowButton.setText(_translate("MainWindow", "Войти"))
        self.RegistrButton.setText(_translate("MainWindow", "Зарегистрировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
