# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sing_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 450)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AuthorizationButton = QtWidgets.QPushButton(self.centralwidget)
        self.AuthorizationButton.setGeometry(QtCore.QRect(440, 340, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.AuthorizationButton.setFont(font)
        self.AuthorizationButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AuthorizationButton.setStyleSheet("QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: rgb(85, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgb(85, 0, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: white;\n"
"}\n"
"")
        self.AuthorizationButton.setObjectName("AuthorizationButton")
        self.RegistrationWindowButton = QtWidgets.QPushButton(self.centralwidget)
        self.RegistrationWindowButton.setGeometry(QtCore.QRect(130, 340, 200, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.RegistrationWindowButton.setFont(font)
        self.RegistrationWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RegistrationWindowButton.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    border-radius: 6px;\n"
"    background-color: white;\n"
"    color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-radius: 6px;\n"
"    background-color: rgbrgb(240, 255, 255);\n"
"    color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-radius: 6px;\n"
"    background-color: #BEB775;\n"
"    color: black;\n"
"}\n"
"")
        self.RegistrationWindowButton.setObjectName("RegistrationWindowButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 130, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 230, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border: 1px solid rgb(186, 186, 186);\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"color: black;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 50, 540, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setStyleSheet("color: black;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация"))
        self.AuthorizationButton.setText(_translate("MainWindow", "Вход"))
        self.RegistrationWindowButton.setText(_translate("MainWindow", "Создать аккаунт"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Логин"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.label.setText(_translate("MainWindow", "Вход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
